### ISSUE TITLE
The "regularised" parameter seems to have no effect

### ISSUE THREAD

**Issue by ghost** [matt-sutton/bigsgPLS#1]
I am trying to use this package to obtain a sparse group PLS solution, but the regularised parameter seems to have no effect on the solution. Consider the following example:

    library(mlbench, bigsgPLS)
    data("BostonHousing")
    x = as.matrix(BostonHousing[, -c(2, 4, 9, 10, 14)]) # Remove categorical variables
    y = BostonHousing[,14]
    ncomp = 9

    index = c(1, 3, 6, 9, 12, 13)
    spls_1 = bigsgpls(X=x, Y=y, regularised="sparse group", H=5, alpha.x=0.5, case=4, ind.block.x = index)
    p_sgpls = spls_1$loadings$X

    pls_1 = bigsgpls(X=x, Y=y, regularised="none", H=5, case=4)
    p_pls = pls_1$loadings$X

    sum(abs(p_sgpls-p_pls)>1e-3)
    >0

So the matrix of loadings obtained using the "sparse group" alternative is the same as the one obtained using the "none" alternative.

Additionally, I am confused on how to control the level of sparsity applied on the sparse regularization alternatives. In the formulation provided in the paper, there seems to be two parameters lambda that control the sparsity applied, but I am unable to find these parameters on the R formulation of the algorithm.

**Comment by matt-sutton** [comment]
Hi sorry for the delayed response - I had some issues with my GitHub email and have just seen this. Thanks for your interest in the package. Unfortunately there were a couple of small issues previously, including for the setting where the data was a matrix rather than a bigdata type so I've corrected these now and I also recommend a couple of syntax changes which are included below. To use the package I would advise reinstalling first to get the corrected version of the package. The following should show how to implement the sparse group PLS method:

```
library(mlbench,bigsgPLS)
data("BostonHousing")
x = as.matrix(BostonHousing[, -c(2, 4, 9, 10, 14)]) # Remove categorical variables
y = as.matrix(BostonHousing[,14])
ncomp = 3

pls_1 = bigsgpls(X=x, Y=y, regularised="none", H=ncomp, case=4)
p_pls <- pls_1$loadings$X

# The group index 
# groups are variables 1-2, 3-6, 6-9.
group.index = c(2, 6) 
sgpls_1 = bigsgpls(X=x, Y=y, regularised="sparse group", H=ncomp,
                  keepX = rep(1,ncomp),alpha.x=0.1, case=4, ind.block.x = index)
p_sgpls <- sgpls_1$loadings$X

sum(abs(p_sgpls-p_pls)>1e-3)
> 27

pred.fit <- predict.bigsgPLS(sgpls_1, newX = x, ng = 1, comps = 3)
```

I hope I'm not sending this too late to be useful! Apologies again for the delay and please let me know if you'd like any more clarification.
